# Azure DevOps pipeline to do periodic dependency upgrade
#

# A pipeline with no CI trigger, just schedules
trigger: none
pr: none

variables:
  system.debug: true

schedules:
  - cron: "0 0 * * *"
    displayName: Daily midnight build
    branches:
      include:
      - master
    always: true # Run always irrespective of changes

resources:
  repositories:
    - repository: pagopaCommons
      type: github
      name: pagopa/azure-pipeline-templates
      ref: refs/tags/v12
      endpoint: 'pagopa'


# Execute agents (jobs) on latest Ubuntu version.
# To change OS for a specific, ovverride "pool" attribute inside the job definition
pool:
  vmImage: 'ubuntu-latest'


jobs:
  - job: do_upgrade
    steps:
      #Call the Yarn.lock updated the first time
      - template: templates/yarn-lock-upgrade/template.yaml@pagopaCommons

